CREATE TABLE "USER"(
	USER_ID VARCHAR2(20),
	USER_PW VARCHAR2(20),
	USER_NAME VARCHAR2(20),
	USER_GENDER VARCHAR2(20),
	USER_EMAIL VARCHAR2(50),
	PRIMARY KEY(USER_ID)
);

INSERT INTO "USER" VALUES('gildong', 123, '홍길동','남자','gildong@naver.com');

SELECT USER_PW FROM "USER" WHERE USER_ID = 'gildong';

COMMIT;

CREATE TABLE MEMBER(
	USER_ID VARCHAR2(20),
	USER_PW VARCHAR2(20),
	USER_NAME VARCHAR2(20),
	USER_GENDER VARCHAR2(20),
	USER_EMAIL VARCHAR2(50),
	PRIMARY KEY(USER_ID)
);

INSERT INTO MEMBER VALUES('gildong', 123, '홍길동','남자','gildong@naver.com');

COMMIT;

CREATE TABLE BOARD(
	BOARD_ID NUMBER,
	BOARD_TITLE VARCHAR2(50),
	USER_ID VARCHAR2(20),
	BOARD_DATE DATE,
	BOARD_CONTENT VARCHAR2(4000),
	BOARD_AVAILABLE NUMBER,
	PRIMARY KEY(BOARD_ID)
);

COMMIT;

-- 작성일자
SELECT TO_CHAR(SYSDATE,'YYYY-MM-DD') FROM DUAL; 
