
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;


CREATE USER board_user IDENTIFIED BY board1234;

GRANT RESOURCE, CONNECT TO board_user;

ALTER USER	board_user 	DEFAULT TABLESPACE SYSTEM QUOTA UNLIMITED ON SYSTEM;


-- 2월 1일 새로운 프로젝트 생성하기
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER myProject IDENTIFIED BY project1234;

-- 권한 부여(접속관련, 객체생성관련, 뷰생성)
GRANT CONNECT, RESOURCE, CREATE VIEW TO myProject;

-- 객체 생성 공간 할당
ALTER USER myProject DEFAULT TABLESPACE SYSTEM
QUOTA UNLIMITED ON SYSTEM;