CREATE TABLE "USER"(
	USER_ID VARCHAR2(20),
	USER_PW VARCHAR2(20),
	USER_NAME VARCHAR2(20),
	USER_GENDER VARCHAR2(20),
	USER_EMAIL VARCHAR2(50),
	PRIMARY KEY(USER_ID)
);

INSERT INTO "USER" VALUES('gildong', 123, '홍길동','남자','gildong@naver.com');

SELECT USER_PW FROM "USER" WHERE USER_ID = 'gildong';