CREATE TABLE "USER"(
	USER_ID VARCHAR2(20),
	USER_PW VARCHAR2(20),
	USER_NAME VARCHAR2(20),
	USER_GENDER VARCHAR2(20),
	USER_EMAIL VARCHAR2(50),
	PRIMARY KEY(USER_ID)
);

INSERT INTO "USER" VALUES('gildong', 123, '홍길동','남자','gildong@naver.com');

SELECT USER_PW FROM "USER" WHERE USER_ID = 'gildong';

COMMIT;

CREATE TABLE MEMBER(
	USER_ID VARCHAR2(20),
	USER_PW VARCHAR2(20),
	USER_NAME VARCHAR2(20),
	USER_GENDER VARCHAR2(20),
	USER_EMAIL VARCHAR2(50),
	PRIMARY KEY(USER_ID)
);

INSERT INTO MEMBER VALUES('gildong', 123, '홍길동','남자','gildong@naver.com');

COMMIT;

CREATE TABLE BOARD(
	BOARD_ID NUMBER,
	BOARD_TITLE VARCHAR2(50),
	USER_ID VARCHAR2(20),
	BOARD_DATE DATE,
	BOARD_CONTENT VARCHAR2(4000),
	BOARD_AVAILABLE NUMBER,
	PRIMARY KEY(BOARD_ID)
);

COMMIT;

-- 작성일자
SELECT SYSDATE  FROM DUAL;
SELECT TO_CHAR(SYSDATE,'YYYY-MM-DD') FROM DUAL; 
SELECT TO_CHAR(SYSDATE,'YYYY-MM-DD HH24:MI:SS') FROM DUAL; -- 시분초까지?

-- 게시글 목록 
-- 이게안됨
-- SELECT * FROM BOARD WHERE BOARD_ID < 2 AND BOARD_AVAILABLE =1 ORDER BY BOARD_ID DESC LIMIT 10;

SELECT * FROM (SELECT * FROM BOARD ORDER BY BOARD_ID) WHERE ROWNUM = 1;

-- 이게 맞다

SELECT * FROM (SELECT * FROM BOARD ORDER BY BOARD_ID) WHERE ROWNUM < 3;
SELECT * FROM (SELECT * FROM BOARD ORDER BY BOARD_ID) WHERE BOARD_AVAILABLE=1 AND ROWNUM < 3 ORDER BY BOARD_ID DESC;
-- 내림차순 추가해봄

SELECT BOARD_ID FROM BOARD ORDER BY BOARD_ID DESC;

-- 게시글 수정
UPDATE BOARD SET BOARD_TITLE = ?, BOARD_CONTENT = ? WHERE BOARD_ID = ?;

-- 게시글 삭제
UPDATE BOARD SET BOARD_AVAILABLE = 0 WHERE BOARD_ID =?

